# Generated by Django 5.2.4 on 2025-07-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
